using System.Text.RegularExpressions;

namespace audit.Objects
{
    /// <summary>
    /// Line-based helpers used by "init" to read settings from, and merge the audit into, the project's own
    /// Azure DevOps pipelines. Text is edited in place (instead of round-tripping through a YAML serializer)
    /// so the customer's comments, ordering and formatting are preserved.
    /// </summary>
    internal static class PipelineYamlMerger
    {
        public const string AuditJobTemplate = ".tasks/audit-review-job.yml";
        public const string RunAuditReviewVariable = "RunAuditReview";

        private static readonly Regex TopLevelKey = new(@"^[A-Za-z_][\w.-]*\s*:");

        #region Readers

        /// <summary>
        /// Whether the CD-Containers pipeline already references the audit job.
        /// </summary>
        public static bool IsAuditMerged(string cdContainers) => cdContainers.Contains(AuditJobTemplate);

        /// <summary>
        /// Whether the pipeline declares a stage named <paramref name="stageName"/>.
        /// </summary>
        public static bool HasStage(string pipeline, string stageName) =>
            Regex.IsMatch(pipeline, $@"(?m)^\s*-\s*stage\s*:\s*{Regex.Escape(stageName)}\s*$");

        /// <summary>
        /// Whether the pipeline declares a runtime parameter named <paramref name="parameterName"/> (case-insensitive,
        /// as Azure DevOps template expressions are).
        /// </summary>
        public static bool HasParameter(string pipeline, string parameterName) =>
            FindParameter(Split(pipeline), parameterName) >= 0;

        /// <summary>
        /// Resolves the expression the CD-Containers pipeline uses to identify the target environment:
        /// an explicit "Environment" parameter, or the variables generated by cmf-pipeline init v2 (env/ branch codename) or v1.
        /// </summary>
        public static string? ResolveEnvironmentExpression(string cdContainers)
        {
            if (HasParameter(cdContainers, "Environment"))
            {
                return "${{ parameters.Environment }}";
            }
            if (cdContainers.Contains("CustomerEnvironmentCodename"))
            {
                return "$(CustomerEnvironmentCodename)";
            }
            if (cdContainers.Contains("CustomerEnvironmentName"))
            {
                return "$(CustomerEnvironmentName)";
            }
            return null;
        }

        /// <summary>
        /// Reads the allowed values and default of the "Environment" runtime parameter, if declared.
        /// </summary>
        public static (List<string> Values, string? Default) ReadEnvironmentParameter(string pipeline)
        {
            var lines = Split(pipeline);
            var values = new List<string>();
            string? defaultValue = null;

            var start = FindParameter(lines, "Environment");
            if (start < 0)
            {
                return (values, defaultValue);
            }

            var itemIndent = Indentation(lines[start]);
            var inValues = false;
            for (var i = start + 1; i < lines.Count; i++)
            {
                var line = lines[i];
                if (string.IsNullOrWhiteSpace(line) || line.TrimStart().StartsWith('#'))
                {
                    continue;
                }
                var indent = Indentation(line);
                if (indent <= itemIndent && (line.TrimStart().StartsWith('-') || TopLevelKey.IsMatch(line)))
                {
                    break;
                }

                var trimmed = line.Trim();
                if (trimmed.StartsWith("default:"))
                {
                    defaultValue = Unquote(trimmed["default:".Length..]);
                    inValues = false;
                }
                else if (trimmed.StartsWith("values:"))
                {
                    inValues = true;
                }
                else if (inValues && trimmed.StartsWith('-'))
                {
                    values.Add(Unquote(trimmed[1..]));
                }
                else
                {
                    inValues = false;
                }
            }

            return (values, string.IsNullOrEmpty(defaultValue) ? null : defaultValue);
        }

        /// <summary>
        /// Reads the agent pool name from the top-level "pool" block.
        /// </summary>
        public static string? ReadPoolName(string pipeline)
        {
            var match = Regex.Match(pipeline, @"(?m)^pool:[ \t]*\r?\n[ \t]+name:[ \t]*(?<value>[^\r\n#]+)");
            return match.Success ? Unquote(match.Groups["value"].Value) : null;
        }

        /// <summary>
        /// Reads a property (e.g. endpoint, options) of the "build-runner" container resource.
        /// </summary>
        public static string? ReadBuildRunnerProperty(string pipeline, string property)
        {
            var lines = Split(pipeline);
            var start = lines.FindIndex(l => Regex.IsMatch(l, @"^\s*-\s*container\s*:\s*build-runner\s*$"));
            if (start < 0)
            {
                return null;
            }

            var itemIndent = Indentation(lines[start]);
            for (var i = start + 1; i < lines.Count; i++)
            {
                var line = lines[i];
                if (string.IsNullOrWhiteSpace(line) || line.TrimStart().StartsWith("//") || line.TrimStart().StartsWith('#'))
                {
                    continue;
                }
                if (Indentation(line) <= itemIndent)
                {
                    break;
                }
                var match = Regex.Match(line, $@"^\s*{Regex.Escape(property)}\s*:\s*(?<value>.+?)\s*$");
                if (match.Success)
                {
                    return Unquote(match.Groups["value"].Value);
                }
            }
            return null;
        }

        /// <summary>
        /// Reads a variable from a mapping-style variables file (e.g. Builds/.vars/global.yml).
        /// </summary>
        public static string? ReadVariable(string variablesFile, string name)
        {
            var match = Regex.Match(variablesFile, $@"(?m)^[ \t]+{Regex.Escape(name)}[ \t]*:[ \t]*(?<value>[^\r\n#]*)");
            if (match.Success)
            {
                var value = Unquote(match.Groups["value"].Value);
                return string.IsNullOrEmpty(value) ? null : value;
            }
            return null;
        }

        #endregion

        #region Writers

        /// <summary>
        /// Adds a variable (with a leading comment) to the end of a variables file, if not already defined.
        /// Supports both the mapping form ("  Name: value") and the list form ("- name: Name").
        /// </summary>
        public static string AddVariable(string variablesFile, string name, string value, string comment)
        {
            var newline = DetectNewline(variablesFile);
            var lines = Split(variablesFile);
            var start = FindTopLevelKey(lines, "variables");
            if (start < 0)
            {
                throw new InvalidOperationException("No top-level 'variables' block found.");
            }
            var end = FindBlockEnd(lines, start);

            var firstItem = lines.Skip(start + 1).Take(end - start - 1).FirstOrDefault(l => !string.IsNullOrWhiteSpace(l) && !l.TrimStart().StartsWith('#'));
            var indent = firstItem == null ? "  " : new string(' ', Indentation(firstItem));
            var isList = firstItem?.TrimStart().StartsWith('-') ?? false;

            if (isList ? Regex.IsMatch(variablesFile, $@"(?m)^\s*-\s*name\s*:\s*{Regex.Escape(name)}\s*$")
                       : Regex.IsMatch(variablesFile, $@"(?m)^[ \t]+{Regex.Escape(name)}[ \t]*:"))
            {
                return variablesFile;
            }

            var block = isList
                ? new List<string> { $"{indent}# {comment}", $"{indent}- name: {name}", $"{indent}  value: {value}" }
                : new List<string> { $"{indent}# {comment}", $"{indent}{name}: {value}" };
            lines.InsertRange(end, block);
            return Join(lines, newline);
        }

        /// <summary>
        /// Merges the audit (runtime parameters, variables and the AuditReview stage) into a CD-Containers pipeline.
        /// The stage is appended at the end of the stages so that no existing stage starts implicitly depending on it.
        /// </summary>
        /// <param name="cdContainers">The pipeline content.</param>
        /// <param name="environmentExpression">Expression that resolves the target environment (see <see cref="ResolveEnvironmentExpression"/>).</param>
        /// <param name="securityAccessTokenSecretName">Default name of the secret variable holding the audit's security access token.</param>
        /// <param name="runAuditReviewVariableValue">When set, also declares the RunAuditReview variable in the pipeline itself (used when there is no global.yml).</param>
        public static string MergeIntoCdContainers(string cdContainers, string environmentExpression, string securityAccessTokenSecretName, string? runAuditReviewVariableValue = null)
        {
            if (IsAuditMerged(cdContainers))
            {
                return cdContainers;
            }

            var newline = DetectNewline(cdContainers);
            var lines = Split(cdContainers);

            // Stage (appended first, as it sits at the end of the file and does not shift the other blocks)
            var stagesStart = FindTopLevelKey(lines, "stages");
            if (stagesStart < 0)
            {
                throw new InvalidOperationException("No top-level 'stages' block found.");
            }
            InsertListItems(lines, stagesStart, FindBlockEnd(lines, stagesStart),
            [
                "",
                "- stage: AuditReview",
                "  displayName: Audit Review",
                "  dependsOn: RunTests",
                "  condition: |",
                "    and(",
                "      or(",
                $"        and(eq('${{{{ parameters.ExecuteAllStages }}}}', true), in(dependencies.RunTests.result, 'Succeeded', 'SucceededWithIssues'), eq(variables['{RunAuditReviewVariable}'], true)),",
                $"        and(eq('${{{{ parameters.ExecuteAllStages }}}}', false), eq('${{{{ parameters.{RunAuditReviewVariable} }}}}', true))",
                "      ),",
                "      not(failed()),",
                "      not(canceled())",
                "    )",
                "  jobs:",
                $"  - template: {AuditJobTemplate}",
                "    parameters:",
                $"      Environment: {environmentExpression}",
                "      SecurityAccessTokenSecretName: ${{ parameters.SecurityAccessTokenSecretName }}",
                "      SecurityAccessTokenOverride: $(SecurityAccessTokenOverride)",
            ]);

            // Runtime parameters, right after the RunTests one when present
            List<string> parameters =
            [
                $"- name: {RunAuditReviewVariable}",
                "  displayName: Run Audit Review",
                "  type: boolean",
                "  default: false",
                "# Name of the secret pipeline variable (Library) holding the audit's security access token.",
                "# Ignored when SecurityAccessTokenOverride is set at queue time.",
                "- name: SecurityAccessTokenSecretName",
                "  displayName: Audit Review Security Access Token Secret Name",
                "  type: string",
                $"  default: {securityAccessTokenSecretName}",
            ];
            var parametersStart = FindTopLevelKey(lines, "parameters");
            if (parametersStart < 0)
            {
                lines.InsertRange(stagesStart, ["parameters:", .. parameters, ""]);
            }
            else
            {
                var parametersEnd = FindBlockEnd(lines, parametersStart);
                var runTests = FindParameter(lines, "RunTests");
                var insertAt = runTests >= 0 ? FindListItemEnd(lines, runTests, parametersEnd) : parametersEnd;
                InsertListItems(lines, parametersStart, insertAt, parameters);
            }

            // Variables
            List<string> variables =
            [
                "# Ad hoc security access token for the Audit Review stage, for one-off runs without a pre-registered secret.",
                "# Leave blank to use SecurityAccessTokenSecretName instead. To set this, use the \"Variables\" tab",
                "# (not \"Parameters\") when queuing the run, and tick \"Keep this value secret\" - never set a real",
                "# token here or as a parameter, since parameter values are shown in plain text in the run summary.",
                "- name: SecurityAccessTokenOverride",
                "  value: ''",
            ];
            if (runAuditReviewVariableValue != null)
            {
                variables.AddRange(
                [
                    "# Defines if the CD-Containers should run the Audit Review after Run Tests",
                    $"- name: {RunAuditReviewVariable}",
                    $"  value: {runAuditReviewVariableValue}",
                ]);
            }
            var variablesStart = FindTopLevelKey(lines, "variables");
            if (variablesStart < 0)
            {
                lines.InsertRange(FindTopLevelKey(lines, "parameters"), ["variables:", .. variables, ""]);
            }
            else
            {
                InsertListItems(lines, variablesStart, FindBlockEnd(lines, variablesStart), variables);
            }

            return Join(lines, newline);
        }

        #endregion

        #region Private Helpers

        private static List<string> Split(string content) =>
            content.Replace("\r\n", "\n").Split('\n').ToList();

        private static string DetectNewline(string content) => content.Contains("\r\n") ? "\r\n" : "\n";

        private static string Join(List<string> lines, string newline) => string.Join(newline, lines);

        private static int Indentation(string line) => line.Length - line.TrimStart(' ').Length;

        private static string Unquote(string value) => value.Trim().Trim('\'', '"');

        private static int FindTopLevelKey(List<string> lines, string key) =>
            lines.FindIndex(l => Regex.IsMatch(l, $@"^{Regex.Escape(key)}\s*:\s*(#.*)?$"));

        /// <summary>
        /// Index right after the last content line of the block that starts at <paramref name="start"/>;
        /// trailing blank lines and column-0 comments belong to whatever follows the block.
        /// </summary>
        private static int FindBlockEnd(List<string> lines, int start)
        {
            var end = start + 1;
            while (end < lines.Count && !TopLevelKey.IsMatch(lines[end]))
            {
                end++;
            }
            while (end - 1 > start && (string.IsNullOrWhiteSpace(lines[end - 1]) || lines[end - 1].StartsWith('#')))
            {
                end--;
            }
            return end;
        }

        /// <summary>
        /// Index right after the list item that starts at <paramref name="start"/> (stopping at the next sibling item,
        /// or at a comment placed at the item's indentation, which documents the next sibling).
        /// </summary>
        private static int FindListItemEnd(List<string> lines, int start, int blockEnd)
        {
            var itemIndent = Indentation(lines[start]);
            var end = start + 1;
            while (end < blockEnd)
            {
                var line = lines[end];
                if (!string.IsNullOrWhiteSpace(line) && Indentation(line) <= itemIndent)
                {
                    break;
                }
                end++;
            }
            return end;
        }

        /// <summary>
        /// Index of the runtime parameter named <paramref name="name"/> inside the top-level "parameters" block, or -1.
        /// </summary>
        private static int FindParameter(List<string> lines, string name)
        {
            var start = FindTopLevelKey(lines, "parameters");
            if (start < 0)
            {
                return -1;
            }
            var end = FindBlockEnd(lines, start);
            var index = lines.FindIndex(start + 1, end - start - 1,
                l => Regex.IsMatch(l, $@"^\s*-\s*name\s*:\s*['""]?{Regex.Escape(name)}['""]?\s*$", RegexOptions.IgnoreCase));
            return index;
        }

        /// <summary>
        /// Inserts <paramref name="items"/> at <paramref name="insertAt"/>, re-indented to match the block's existing list items.
        /// </summary>
        private static void InsertListItems(List<string> lines, int blockStart, int insertAt, List<string> items)
        {
            var firstItem = lines.Skip(blockStart + 1).FirstOrDefault(l => l.TrimStart().StartsWith('-'));
            var indent = firstItem == null ? string.Empty : new string(' ', Indentation(firstItem));
            lines.InsertRange(insertAt, items.Select(item => item.Length == 0 ? item : indent + item));
        }

        #endregion
    }
}
