

using Cmf.Community.IoTCustomAutomationConfiguration.Actions.Orchestration.InputObjects;
using Cmf.Community.IoTCustomAutomationConfiguration.Actions.Orchestration.OutputObjects;

namespace Cmf.Community.IoTCustomAutomationConfiguration.Actions.Orchestration;

public interface ICustomAutomationConfigurationOrchestration
{
    public CustomAutomationCreateConfigurationMetadataOutput CustomAutomationCreateConfigurationMetadata(CustomAutomationCreateConfigurationMetadataInput customAutomationCreateConfigurationMetadataInput);

    public CustomAutomationCreateConfigurationEntitiesOutput CustomAutomationCreateConfigurationEntities(CustomAutomationCreateConfigurationEntitiesInput customAutomationCreateConfigurationEntitiesInput);

    public CustomAutomationRetrieveConfigurationOutput CustomAutomationRetrieveConfiguration(CustomAutomationRetrieveConfigurationInput customAutomationRetriveConfigurationInput);

    public CustomAutomationCreateRelatedEntityRelationOnConnectIoTEnabledOutput CustomAutomationCreateRelatedEntityRelationOnConnectIoTEnabled(CustomAutomationCreateRelatedEntityRelationOnConnectIoTEnabledInput customAutomationCreateRelatedEntityRelationOnConnectIoTEnabledInput);

    public CustomAutomationUpdateConfigurationEntitiesOutput CustomAutomationUpdateConfigurationEntities(CustomAutomationUpdateConfigurationEntitiesInput customAutomationUpdateConfigurationEntitiesInput);
}