#!/usr/bin/env bash
#
# Bash port of .rebuildDatabase.ps1.
#
# Scans a directory for *.tgz npm packages and rebuilds .repositoryContent.json:
# a directory listing (packageName -> version -> filename) describing a
# local, offline npm-style repository of packages (IoT DataPlatform / Connect
# IoT tooling reads packages from a directory like this).
#
# Usage: .rebuildDatabase.sh [dir]   (defaults to this script's own directory)
#
# Note: the original .ps1 ends with a 5-second Start-Sleep so a
# double-clicked Windows console window doesn't close before you can read the
# output. There's no equivalent need in a terminal, so it's omitted here.
set -euo pipefail

log()       { printf '[INFO] %s\n' "$*"; }
log_error() { printf '\033[31m[ERROR] %s\033[0m\n' "$*" >&2; }

command -v tar >/dev/null 2>&1 || { log_error "tar is required but was not found on PATH"; exit 1; }
command -v jq  >/dev/null 2>&1 || { log_error "jq is required but was not found on PATH"; exit 1; }

DIR="${1:-$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)}"

log "** IoT DataPlatform / Connect IoT Directory Repository **"
log "** Rebuilding database of deployed packages **"

mapfile -t FILES < <(find "$DIR" -maxdepth 1 -name '*.tgz' | sort)
log "Found ${#FILES[@]} files in $DIR"

declare -A SEEN
ENTRIES=()

for file in "${FILES[@]}"; do
  name_version=$(tar -xOf "$file" package/package.json | jq -r '"\(.name)\t\(.version)"')
  name="${name_version%%$'\t'*}"
  version="${name_version#*$'\t'}"
  log "   Found '$name', version '$version'"

  key="$name@$version"
  if [ -n "${SEEN[$key]:-}" ]; then
    log_error "Duplicated '$name', version '$version' found. Ignored!"
    continue
  fi
  SEEN["$key"]=1
  ENTRIES+=("$name"$'\t'"$version"$'\t'"$(basename "$file")")
done

GENERATED_AT="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

if [ ${#ENTRIES[@]} -eq 0 ]; then
  ENTRIES_INPUT=""
else
  ENTRIES_INPUT=$(printf '%s\n' "${ENTRIES[@]}")
fi

jq -R -s \
  --arg type "Node Packages Directory Repository for IoT DataPlatform / Connect IoT" \
  --arg description "This file is autogenerated! Use the .rebuildDatabase.sh script to rebuild it" \
  --arg generatedAt "$GENERATED_AT" \
  '
    (split("\n") | map(select(length > 0) | split("\t") | {name: .[0], version: .[1], filename: .[2]})) as $entries
    | {
        "$type": $type,
        description: $description,
        generatedAt: $generatedAt,
        packages: ($entries | group_by(.name) | map({
          key: .[0].name,
          value: (map({(.version): .filename}) | add)
        }) | from_entries)
      }
  ' <<< "$ENTRIES_INPUT" > "$DIR/.repositoryContent.json"

log ""
log "** Finished **"
log ""
log "Wrote $DIR/.repositoryContent.json"
