<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<OutputType>Library</OutputType>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<AssemblyName>Cmf.Community.TimeTracking.Services</AssemblyName>
		<RootNamespace>Cmf.Community.TimeTracking.Services</RootNamespace>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<OutputPath>../../LocalEnvironment\BusinessTier</OutputPath>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<OutputPath>..\Release</OutputPath>
	</PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="..\Cmf.Community.TimeTracking.Orchestration\Cmf.Community.TimeTracking.Orchestration.csproj" />
	</ItemGroup>
</Project>